# Generated by Django 4.0.2 on 2022-03-09 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('short_description', models.CharField(default='Описание', max_length=100, verbose_name='Краткое описание')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Слоган')),
                ('information', models.TextField(verbose_name='Информация курса')),
                ('picture', models.ImageField(upload_to='courses/', verbose_name='Обложка курса')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='LessonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Категория урока')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_cat_course', to='lms.course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Категория урока',
                'verbose_name_plural': 'Категории уроков',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название видео')),
                ('file', models.URLField(verbose_name='Видео-урок')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lms.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('lecture', models.TextField(verbose_name='Лекция')),
                ('task_question_file', models.FileField(blank=True, null=True, upload_to='task_question/', verbose_name='Файл с задачами')),
                ('task_solution_file', models.FileField(blank=True, null=True, upload_to='task_solution/', verbose_name='Файл решением')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Баллы учителя')),
                ('true_solution', models.TextField(verbose_name='Правильное решение')),
                ('initial_data', models.DateField(default=datetime.date.today, verbose_name='Срок')),
                ('type', models.CharField(default='lection', max_length=50, verbose_name='Тип урока')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершенность курса')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('lesson_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_lessons', to='lms.lessoncategory', verbose_name='Категория урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Группы')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Старт курса')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
