# Generated by Django 4.0.3 on 2022-03-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_delete_video_review_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(null=True, upload_to='courses/', verbose_name='Обложка курса'),
        ),
    ]
