# Generated by Django 4.0.2 on 2022-03-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_delete_video_review_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=10, verbose_name='Цвет'),
        ),
    ]
