# Generated by Django 4.0.2 on 2022-03-04 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0002_delete_task'),
        ('accounts', '0002_delete_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание')),
                ('initial_data', models.DateField(default=datetime.date.today, verbose_name='Срок')),
                ('scores', models.PositiveSmallIntegerField(default=1, verbose_name='Баллы')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('lessons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.lessons', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_solution', models.TextField(verbose_name='Ответ пользователя')),
                ('true_solution', models.TextField(verbose_name='Правильный ответ')),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.task', verbose_name='Задача')),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
